### ISSUE TITLE
[fix]: arrow icon not changing to arrow-down icon

### ISSUE THREAD

**Issue by vikasganiga05** [coding-in-public/accessible-accordion-component#1]
When the accordion is open the arrow icon of the previously opened accordion is not changing to the arrow-down icon.

### Screenshot
![image](https://user-images.githubusercontent.com/74750414/144067831-1cd081b3-4407-4c09-a097-9e3586ee39d0.png)

**Comment by coding-in-public** [comment]
Hey! You’re right, @vikasganiga05! I don't know how I missed this! If I get around to it, I’ll do a PR myself later today unless someone else gets around to it first. Thanks!

**Comment by coding-in-public** [comment]
Okay, yeah, I just needed to add one more little loop through the buttons. So I'll just do the PR now. Thanks again!

**Comment by vikasganiga05** [comment]
> Okay, yeah, I just needed to add one more little loop through the buttons. So I'll just do the PR now. Thanks again!

Your welcome :+1:
